# deploy-template.yml
steps:
  - uses: actions/checkout@v3
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.9
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install .

  - name: Create Service Unit File
    run: |
      cat << EOF > /etc/systemd/system/pollect.service
      [Unit]
      Description=Pollect service
      After=network.target
      
      [Service]
      Environment="VSPHERE_USERNAME=${{ inputs.VSPHERE_USERNAME }}"
      Environment="VSPHERE_PASSWORD=${{ inputs.VSPHERE_PASSWORD }}"
      ExecStart=/usr/bin/python3 -m pollect --config planetary-configs/${{ inputs.POLLECT_CONFIG_FILE }}"
      WorkingDirectory=/opt/actions-runner/planetary-pollect/planetary-pollect/
      Restart=always
      
      [Install]
      WantedBy=multi-user.target
      EOF

  - name: Terminate old pollect instance
    run: |
      systemctl stop pollect
  - name: Run pollect
    run: |
      systemctl daemon-reload
      systemctl enable pollect
      systemctl start pollect
