name: Deploy pollect on VMs

on:
  push:
    branches: [ 'main', 'sources' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.planetary_exp }}
    strategy:
      matrix:
        planetary_exp: ['local-planetary-exp-erl', 'local-planetary-exp-khe']
        config_file: ['erl-config.yml', 'khe-config.yml']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Create Service Unit File
        run: |
          cat << EOF > /etc/systemd/system/pollect.service
          [Unit]
          Description=Pollect service
          After=network.target

          [Service]
          Environment="VSPHERE_USERNAME=${{ secrets.VSPHERE_USERNAME }}"
          Environment="VSPHERE_PASSWORD=${{ secrets.VSPHERE_PASSWORD }}"
          ExecStart=/usr/bin/python3 -m pollect --config planetary-configs/${{ matrix.config_file }}"
          WorkingDirectory=/opt/actions-runner/planetary-pollect/planetary-pollect/
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF
          
      - name: Terminate old pollect instance
        run: |
          systemctl stop pollect.service
          
      - name: Run pollect
        run: |
          systemctl daemon-reload
          systemctl enable pollect.service
          systemctl start pollect.service
          
      - name: Check if pollect exposes metrics
        run: |
          sleep 10
          curl -f localhost:9101/metrics    
      
