name: Deploy pollect on VMs

on:
  push:
    branches: [ 'main', 'sources' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.planetary_exp }}
    strategy:
      matrix:
        include:
          - planetary_exp: 'local-planetary-exp-erl'
            config_file: 'erl-config.yml'
            location: 'ERL'
          - planetary_exp: 'local-planetary-exp-khe'
            config_file: 'khe-config.yml'
            location: 'KHE'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Create Service Unit File
        env:
          VSPHERE_USERNAME: ${{ secrets[format('VSPHERE_USERNAME_{0}', matrix.location)] }}
          VSPHERE_PASSWORD: ${{ secrets[format('VSPHERE_PASSWORD_{0}', matrix.location)] }}
          POLLECT_CONFIG_FILE: ${{ matrix.config_file }}
        run: |
          sudo cp pollect.service /etc/systemd/system/
      - name: Terminate old pollect instance
        run: |
          fuser -k 9101/tcp
          sudo systemctl stop pollect.service
      - name: Run pollect
        run: |
          sudo systemctl daemon-reload
          sudo systemctl enable pollect.service
          sudo systemctl start pollect.service
      - name: Check metrics
        run: |
          sleep 10
          curl -f localhost:9101/metrics
